return {
    -- Window and Tab Titles
    ["Lurnai - Free Version"] = "Lurnai - Version Gratuite",
    ["By Havoc Home"] = "Par Havoc Home",
    ["Home"] = "Accueil",
    ["Main"] = "Principal",
    ["Rebirths"] = "Renaissances",
    ["Killer"] = "Tueur",
    ["Crystals"] = "Cristaux",
    ["Teleport"] = "Téléportation",
    ["Status"] = "Statut",
    ["Miscellaneous"] = "Divers",
    ["Settings"] = "Paramètres",
    ["Credits"] = "Crédits",
    
    -- Home Tab
    ["Discord Invite"] = "Invitation Discord",
    ["Join our Discord community for updates and support!"] = "Rejoignez notre communauté Discord pour les mises à jour et le support !",
    ["Change Speed"] = "Changer la Vitesse",
    ["Enter speed value"] = "Entrez la valeur de vitesse",
    ["Auto Set Speed"] = "Définir Vitesse Auto",
    ["SpeedInfo"] = "InfoVitesse",
    ["__________________________________________"] = "__________________________________________",
    ["Change Size"] = "Changer la Taille",
    ["Enter size value"] = "Entrez la valeur de taille",
    ["Auto Set Size"] = "Définir Taille Auto",
    ["SizeInfo"] = "InfoTaille",
    ["Anti Knockback"] = "Anti-Recul",
    ["Infinite Jump"] = "Saut Infini",
    ["NoClip"] = "NoClip",
    ["Free AutoLift"] = "AutoLift Gratuit",
    ["Auto Egg"] = "Œuf Auto",
    ["Walk On Water"] = "Marcher sur l'Eau",
    ["FreeEdition"] = "ÉditionGratuite",
    ["Free Edition"] = "Édition Gratuite",
    ["Fast Strength"] = "Force Rapide",
    ["Hide Frames"] = "Cacher les Cadres",
    
    -- Main Tab
    ["Auto Weight"] = "Poids Auto",
    ["Auto Pushups"] = "Pompes Auto",
    ["Auto Situps"] = "Abdos Auto",
    ["Auto Standups"] = "Redressements Auto",
    ["Auto Punch"] = "Coup de Poing Auto",
    ["Auto Stomp"] = "Piétinement Auto",
    ["Auto Slam"] = "Écrasement Auto",
    ["Fast Tools"] = "Outils Rapides",
    ["Workout"] = "Entraînement",
    
    -- Workout Locations
    ["Starter Island"] = "Île de Départ",
    ["Legend Beach"] = "Plage Légendaire",
    ["Frost Gym"] = "Gymnase Glacé",
    ["Mythical Gym"] = "Gymnase Mythique",
    ["Eternal Gym"] = "Gymnase Éternel",
    ["Legend Gym"] = "Gymnase Légendaire",
    ["Muscle King Gym"] = "Gymnase du Roi Musclé",
    ["Jungle Gym"] = "Gymnase de la Jungle",
    
    -- Rock Locations
    ["Tiny Rock"] = "Petit Rocher",
    ["Punching Rock"] = "Rocher de Frappe",
    ["Golden Rock"] = "Rocher Doré",
    ["Frost Rock"] = "Rocher Glacé",
    ["Mythical Rock"] = "Rocher Mythique",
    ["Eternal Rock"] = "Rocher Éternel",
    ["Legend Rock"] = "Rocher Légendaire",
    ["Muscle King Rock"] = "Rocher du Roi Musclé",
    ["Jungle Rock"] = "Rocher de la Jungle",
    
    -- Rebirths Tab
    ["RebirthStatus"] = "StatutRenaissance",
    ["Target Rebirth: 0 Out of % Done"] = "Renaissance Cible : 0 sur % Terminé",
    ["Target Rebirth Goal: 0"] = "Objectif de Renaissance Cible : 0",
    ["RebirthInfo"] = "InfoRenaissance",
    ["Current Rebirths: 0\nRebirths Gained: 0\nTimer: 0 Days, 0 Hours, 0 Minutes, 0 Seconds"] = "Renaissances Actuelles : 0\nRenaissances Gagnées : 0\nChronomètre : 0 Jours, 0 Heures, 0 Minutes, 0 Secondes",
    ["Rebirth Target"] = "Cible de Renaissance",
    ["Enter target"] = "Entrez la cible",
    ["RebirthSeparator"] = "SéparateurRenaissance",
    ["_____________________________________"] = "_____________________________________",
    ["Infinite Rebirths"] = "Renaissances Infinies",
    ["GlitchableRebirth"] = "RenaissanceExploitable",
    ["Next Closest Glitchable Rebirth"] = "Prochaine Renaissance Exploitable la Plus Proche",
    ["Description: Level 1, 0XP"] = "Description : Niveau 1, 0XP",
    ["Closest Glitchable"] = "Exploitable le Plus Proche",
    ["GlitchableInfo"] = "InfoExploitable",
    ["Information about glitchable rebirths will appear here"] = "Les informations sur les renaissances exploitables apparaîtront ici",
    
    -- Killer Tab
    ["Whitelist"] = "Liste Blanche",
    ["Enter player name"] = "Entrez le nom du joueur",
    ["Unwhitelist"] = "Retirer de la Liste Blanche",
    ["Whitelist Friends"] = "Amis en Liste Blanche",
    ["Start Killing"] = "Commencer à Tuer",
    ["KillerSeparator1"] = "SéparateurTueur1",
    ["___________________________________"] = "___________________________________",
    ["Kill Specific Player"] = "Tuer un Joueur Spécifique",
    ["Kill Player"] = "Tuer le Joueur",
    ["Spy On Player"] = "Espionner le Joueur",
    ["KillerSeparator2"] = "SéparateurTueur2",
    ["Auto Kill Good Karma"] = "Tuer Auto Bon Karma",
    ["Auto Kill Bad Karma"] = "Tuer Auto Mauvais Karma",
    
    -- Crystals Tab
    ["Crystal"] = "Cristal",
    ["Auto Crystal"] = "Cristal Auto",
    ["CrystalSeparator"] = "SéparateurCristal",
    ["Auto Pet"] = "Animal Auto",
    ["Enter pet name"] = "Entrez le nom de l'animal",
    ["Auto Open"] = "Ouverture Auto",
    ["Auto Aura"] = "Aura Auto",
    ["Enter aura name"] = "Entrez le nom de l'aura",
    
    -- Status Tab
    ["Timer"] = "Chronomètre",
    ["Time Played: 0 Days, 0 Hours, 0 Minutes, 0 Seconds"] = "Temps Joué : 0 Jours, 0 Heures, 0 Minutes, 0 Secondes",
    ["Stats"] = "Statistiques",
    ["Strength: 0 (0)\nRebirths: 0 (0)\nKills: 0 (0)\nBrawls: 0 (0)\nDurability: 0 (0)\nGood Karma: 0 (0)\nBad Karma: 0 (0)\nAgility: 0 (0)\n    "] = "Force : 0 (0)\nRenaissances : 0 (0)\nTués : 0 (0)\nBagarres : 0 (0)\nEndurance : 0 (0)\nBon Karma : 0 (0)\nMauvais Karma : 0 (0)\nAgilité : 0 (0)\n    ",
    ["StatsSeparator"] = "SéparateurStats",
    ["See Player Stats"] = "Voir les Stats du Joueur",
    
    -- Miscellaneous Tab
    ["FPS Boost"] = "Boost FPS",
    ["Low Graphics"] = "Graphiques Bas",
    ["Rejoin Server"] = "Rejoindre le Serveur",
    ["Low Player Server"] = "Serveur à Faible Population",
    
    -- Credits Tab
    ["Credits"] = "Crédits",
    ["Havoc - Coder - Founder\nMizuuu - Took Care of my Discord Server\nDucks - Awesome Friend\n1_6wk - Awesome Friend\nPremium Buyers - Awesome people for supporting me and my work\n    "] = "Havoc - Codeur - Fondateur\nMizuuu - S'est occupé de mon serveur Discord\nDucks - Ami Génial\n1_6wk - Ami Génial\nAcheteurs Premium - Personnes géniales qui soutiennent mon travail\n    ",
    
    -- Notifications
    ["Welcome To Lurnai Free Version :D"] = "Bienvenue sur la Version Gratuite de Lurnai :D",
    
    -- Additional translations from your format
    ["title"] = "Mise à jour Lurnai",
    ["subtitle"] = "Les enfants ne peuvent pas nous arrêter",
    ["crystal"] = "Cristal",
    ["localPlayer"] = "JoueurLocal",
    ["SetWalkSpeed"] = "Définir Vitesse de Marche",
    ["EnterSpeedValue"] = "Entrer Valeur de Vitesse",
    ["EnableWalkSpeed"] = "Activer Vitesse de Marche",
    ["JumpInfinite"] = "SautInfini",
    ["SizeChanger"] = "Changeur de Taille",
    ["SizeAmount"] = "Quantité de Taille",
    ["TypeHere..."] = "Tapez Ici...",
    ["FarmingGym"] = "Farming Gymnases",
    ["FarmingGeneral"] = "Farming Général",
    ["MISC"] = "Divers",
    ["LockPos"] = "VerrouillerPos",
    ["WalkonWater"] = "Marcher sur l'Eau",
    ["FasterTools"] = "- [ Outils Plus Rapides ] -",
    ["RockFarm"] = "Farming de Rochers",
    ["FarmTinyIslandRock"] = "Farmer Petit Rocher d'Île",
    ["FarmStarterIslandRock"] = "Farmer Rocher d'Île de Départ",
    ["FarmLegendBeachRock"] = "Farmer Rocher de Plage Légendaire",
    ["FarmFrostGymRock"] = "Farmer Rocher de Gymnase Glacé",
    ["FarmMythicalGymRock"] = "Farmer Rocher de Gymnase Mythique",
    ["FarmEternalGymRock"] = "Farmer Rocher de Gymnase Éternel",
    ["FarmMuscleKingGymRock"] = "Farmer Rocher de Gymnase du Roi Musclé",
    ["FarmJungleRock"] = "Farmer Rocher de la Jungle",
    ["Brawl"] = "Bagarre",
    ["AutoJoinBrawl"] = "Rejoindre Auto Bagarre",
    ["AutoWinBrawl"] = "Gagner Auto Bagarre",
    ["RebirthStatistics"] = "Statistiques de Renaissance",
    ["TargetRebirthAmount"] = "Montant Cible de Renaissance",
    ["RebirthFarm1"] = "Farming Renaissance 1",
    ["AutoRebirth(Infinite)"] = "Renaissance Auto (Infinie)",
    ["EnterPlayerUserOrDisplay"] = "Entrer Utilisateur ou Affichage du Joueur",
    ["TypeUsernameHere"] = "Tapez le nom d'utilisateur ici...",
    ["RemoveAllFromWhitelist"] = "Tout Retirer de la Liste Blanche",
    ["AutoWhitelistFriends"] = "Liste Blanche Auto des Amis",
    ["DoesntWorkRN"] = "Ne Fonctionne Pas Maintenant !",
    ["AutoKillEvilKarma"] = "Tuer Auto Mauvais Karma",
    ["FarmingKillPlayer"] = "Farming Tuer Joueur",
    ["EnterPlayerUsernameOrDisplay"] = "Entrer Nom d'Utilisateur ou Affichage du Joueur",
    ["TypeUsernameDisplayHere"] = "Tapez nom d'utilisateur/affichage ici...",
    ["AutoKillPlayer"] = "Tuer Auto Joueur",
    ["SpectatePlayer"] = "Observer le Joueur",
    ["StopSpectating"] = "Arrêter d'Observer",
    ["SelectCrystal"] = "Sélectionner Cristal",
    ["AutoOpenCrystal"] = "Ouverture Auto de Cristal",
    ["SessionTime"] = "Temps de Session",
    ["CustomTimer"] = "Chronomètre Personnalisé",
    ["Start/StopTimer"] = "Démarrer/Arrêter Chronomètre",
    ["CurrentStats"] = "Stats Actuelles",
    ["GainedStats"] = "Stats Gagnées",
    ["PlayerStats"] = "Stats du Joueur",
    ["PlayerSelector"] = "Sélecteur de Joueur",
    ["ViewPlayerStats"] = "Voir les Stats du Joueur",
    ["FPSBOOST"] = "BOOST FPS",
    ["ServerHop"] = "Changer de Serveur",
    ["AutoLift"] = "Levage Auto",
    ["SpeedGrind(No Rebirth)"] = "Grinding Rapide (Sans Renaissance)",
    ["HideFrames"] = "Cacher les Cadres",
    ["SelectPet"] = "Sélectionner Animal",
    ["AutoOpenPets"] = "Ouverture Auto d'Animaux",
    ["AutoOpenAuras"] = "Ouverture Auto d'Auras",
    ["SelectAura"] = "Sélectionner Aura",
    ["AutoUseProteinEgg"] = "Utilisation Auto d'Œuf Protéiné"
}
