return {
    -- Window and Tab Titles
    ["Lurnai - Free Version"] = "Lurnai - Kostenlose Version",
    ["By Havoc Home"] = "Von Havoc Home",
    ["Home"] = "Startseite",
    ["Main"] = "Hauptmenü",
    ["Rebirths"] = "Wiedergeburten",
    ["Killer"] = "Killer",
    ["Crystals"] = "Kristalle",
    ["Teleport"] = "Teleport",
    ["Status"] = "Status",
    ["Miscellaneous"] = "Verschiedenes",
    ["Settings"] = "Einstellungen",
    ["Credits"] = "Mitwirkende",
    
    -- Home Tab
    ["Discord Invite"] = "Discord-Einladung",
    ["Join our Discord community for updates and support!"] = "Tritt unserer Discord-Community für Updates und Support bei!",
    ["Change Speed"] = "Geschwindigkeit ändern",
    ["Enter speed value"] = "Geschwindigkeitswert eingeben",
    ["Auto Set Speed"] = "Auto-Geschwindigkeit",
    ["SpeedInfo"] = "GeschwindigkeitsInfo",
    ["__________________________________________"] = "__________________________________________",
    ["Change Size"] = "Größe ändern",
    ["Enter size value"] = "Größenwert eingeben",
    ["Auto Set Size"] = "Auto-Größe",
    ["SizeInfo"] = "GrößenInfo",
    ["Anti Knockback"] = "Anti-Rückstoß",
    ["Infinite Jump"] = "Unendlicher Sprung",
    ["NoClip"] = "NoClip",
    ["Free AutoLift"] = "Kostenloses AutoLift",
    ["Auto Egg"] = "Auto-Ei",
    ["Walk On Water"] = "Auf Wasser laufen",
    ["FreeEdition"] = "KostenlosVersion",
    ["Free Edition"] = "Kostenlose Version",
    ["Fast Strength"] = "Schnelle Stärke",
    ["Hide Frames"] = "Rahmen ausblenden",
    
    -- Main Tab
    ["Auto Weight"] = "Auto-Gewicht",
    ["Auto Pushups"] = "Auto-Liegestütze",
    ["Auto Situps"] = "Auto-Situps",
    ["Auto Standups"] = "Auto-Aufstehen",
    ["Auto Punch"] = "Auto-Schlag",
    ["Auto Stomp"] = "Auto-Stampfen",
    ["Auto Slam"] = "Auto-Slam",
    ["Fast Tools"] = "Schnelle Werkzeuge",
    ["Workout"] = "Training",
    
    -- Workout Locations
    ["Starter Island"] = "Starter-Insel",
    ["Legend Beach"] = "Legenden-Strand",
    ["Frost Gym"] = "Frost-Fitnessstudio",
    ["Mythical Gym"] = "Mythisches Fitnessstudio",
    ["Eternal Gym"] = "Ewiges Fitnessstudio",
    ["Legend Gym"] = "Legenden-Fitnessstudio",
    ["Muscle King Gym"] = "Muskelkönig-Fitnessstudio",
    ["Jungle Gym"] = "Dschungel-Fitnessstudio",
    
    -- Rock Locations
    ["Tiny Rock"] = "Kleiner Felsen",
    ["Punching Rock"] = "Schlagfelsen",
    ["Golden Rock"] = "Goldener Felsen",
    ["Frost Rock"] = "Frostfelsen",
    ["Mythical Rock"] = "Mythischer Felsen",
    ["Eternal Rock"] = "Ewiger Felsen",
    ["Legend Rock"] = "Legendärer Felsen",
    ["Muscle King Rock"] = "Muskelkönig-Felsen",
    ["Jungle Rock"] = "Dschungelfelsen",
    
    -- Rebirths Tab
    ["RebirthStatus"] = "WiedergeburtsStatus",
    ["Target Rebirth: 0 Out of % Done"] = "Ziel-Wiedergeburt: 0 von % erledigt",
    ["Target Rebirth Goal: 0"] = "Wiedergeburtsziel: 0",
    ["RebirthInfo"] = "WiedergeburtsInfo",
    ["Current Rebirths: 0\nRebirths Gained: 0\nTimer: 0 Days, 0 Hours, 0 Minutes, 0 Seconds"] = "Aktuelle Wiedergeburten: 0\nErhaltene Wiedergeburten: 0\nTimer: 0 Tage, 0 Stunden, 0 Minuten, 0 Sekunden",
    ["Rebirth Target"] = "Wiedergeburtsziel",
    ["Enter target"] = "Ziel eingeben",
    ["RebirthSeparator"] = "WiedergeburtsTrenner",
    ["_____________________________________"] = "_____________________________________",
    ["Infinite Rebirths"] = "Unendliche Wiedergeburten",
    ["GlitchableRebirth"] = "AusnutzbareWiedergeburt",
    ["Next Closest Glitchable Rebirth"] = "Nächste ausnutzbare Wiedergeburt",
    ["Description: Level 1, 0XP"] = "Beschreibung: Level 1, 0XP",
    ["Closest Glitchable"] = "Nächste Ausnutzbare",
    ["GlitchableInfo"] = "AusnutzbareInfo",
    ["Information about glitchable rebirths will appear here"] = "Informationen über ausnutzbare Wiedergeburten erscheinen hier",
    
    -- Killer Tab
    ["Whitelist"] = "Whitelist",
    ["Enter player name"] = "Spielername eingeben",
    ["Unwhitelist"] = "Von Whitelist entfernen",
    ["Whitelist Friends"] = "Freunde auf Whitelist",
    ["Start Killing"] = "Töten starten",
    ["KillerSeparator1"] = "KillerTrenner1",
    ["___________________________________"] = "___________________________________",
    ["Kill Specific Player"] = "Bestimmten Spieler töten",
    ["Kill Player"] = "Spieler töten",
    ["Spy On Player"] = "Spieler ausspionieren",
    ["KillerSeparator2"] = "KillerTrenner2",
    ["Auto Kill Good Karma"] = "Auto-Kill Gutes Karma",
    ["Auto Kill Bad Karma"] = "Auto-Kill Schlechtes Karma",
    
    -- Crystals Tab
    ["Crystal"] = "Kristall",
    ["Auto Crystal"] = "Auto-Kristall",
    ["CrystalSeparator"] = "KristallTrenner",
    ["Auto Pet"] = "Auto-Haustier",
    ["Enter pet name"] = "Haustiername eingeben",
    ["Auto Open"] = "Auto-Öffnen",
    ["Auto Aura"] = "Auto-Aura",
    ["Enter aura name"] = "Auraname eingeben",
    
    -- Status Tab
    ["Timer"] = "Timer",
    ["Time Played: 0 Days, 0 Hours, 0 Minutes, 0 Seconds"] = "Spielzeit: 0 Tage, 0 Stunden, 0 Minuten, 0 Sekunden",
    ["Stats"] = "Statistiken",
    ["Strength: 0 (0)\nRebirths: 0 (0)\nKills: 0 (0)\nBrawls: 0 (0)\nDurability: 0 (0)\nGood Karma: 0 (0)\nBad Karma: 0 (0)\nAgility: 0 (0)\n    "] = "Stärke: 0 (0)\nWiedergeburten: 0 (0)\nKills: 0 (0)\nKämpfe: 0 (0)\nAusdauer: 0 (0)\nGutes Karma: 0 (0)\nSchlechtes Karma: 0 (0)\nBeweglichkeit: 0 (0)\n    ",
    ["StatsSeparator"] = "StatistikTrenner",
    ["See Player Stats"] = "Spielerstatistiken anzeigen",
    
    -- Miscellaneous Tab
    ["FPS Boost"] = "FPS-Boost",
    ["Low Graphics"] = "Niedrige Grafik",
    ["Rejoin Server"] = "Server erneut beitreten",
    ["Low Player Server"] = "Server mit wenigen Spielern",
    
    -- Credits Tab
    ["Credits"] = "Mitwirkende",
    ["Havoc - Coder - Founder\nMizuuu - Took Care of my Discord Server\nDucks - Awesome Friend\n1_6wk - Awesome Friend\nPremium Buyers - Awesome people for supporting me and my work\n    "] = "Havoc - Programmierer - Gründer\nMizuuu - Kümmerte sich um meinen Discord-Server\nDucks - Toller Freund\n1_6wk - Toller Freund\nPremium-Käufer - Großartige Leute, die mich und meine Arbeit unterstützen\n    ",
    
    -- Notifications
    ["Welcome To Lurnai Free Version :D"] = "Willkommen zur kostenlosen Version von Lurnai :D",
    
    -- Additional translations from your format
    ["title"] = "Lurnai Update",
    ["subtitle"] = "Kinder können uns nicht aufhalten",
    ["crystal"] = "Kristall",
    ["localPlayer"] = "LokalerSpieler",
    ["SetWalkSpeed"] = "Gehgeschwindigkeit einstellen",
    ["EnterSpeedValue"] = "Geschwindigkeitswert eingeben",
    ["EnableWalkSpeed"] = "Gehgeschwindigkeit aktivieren",
    ["JumpInfinite"] = "UnendlicherSprung",
    ["SizeChanger"] = "Größenänderung",
    ["SizeAmount"] = "Größenmenge",
    ["TypeHere..."] = "Hier tippen...",
    ["FarmingGym"] = "Fitnessstudio-Farming",
    ["FarmingGeneral"] = "Allgemeines Farming",
    ["MISC"] = "Verschiedenes",
    ["LockPos"] = "PositionSperren",
    ["WalkonWater"] = "AufWasserLaufen",
    ["FasterTools"] = "- [ Schnellere Werkzeuge ] -",
    ["RockFarm"] = "Felsen-Farming",
    ["FarmTinyIslandRock"] = "Kleiner Inselfelsen farmen",
    ["FarmStarterIslandRock"] = "Starter-Inselfelsen farmen",
    ["FarmLegendBeachRock"] = "Legenden-Strandfelsen farmen",
    ["FarmFrostGymRock"] = "Frost-Fitnessstudiofelsen farmen",
    ["FarmMythicalGymRock"] = "Mythischer Fitnessstudiofelsen farmen",
    ["FarmEternalGymRock"] = "Ewiger Fitnessstudiofelsen farmen",
    ["FarmMuscleKingGymRock"] = "Muskelkönig-Fitnessstudiofelsen farmen",
    ["FarmJungleRock"] = "Dschungelfelsen farmen",
    ["Brawl"] = "Kampf",
    ["AutoJoinBrawl"] = "Auto-Kampfbeitritt",
    ["AutoWinBrawl"] = "Auto-Kampfgewinn",
    ["RebirthStatistics"] = "Wiedergeburtsstatistiken",
    ["TargetRebirthAmount"] = "Ziel-Wiedergeburtsmenge",
    ["RebirthFarm1"] = "Wiedergeburts-Farming 1",
    ["AutoRebirth(Infinite)"] = "Auto-Wiedergeburt (Unendlich)",
    ["EnterPlayerUserOrDisplay"] = "Spielerbenutzername oder -anzeige eingeben",
    ["TypeUsernameHere"] = "Benutzername hier eingeben...",
    ["RemoveAllFromWhitelist"] = "Alle von Whitelist entfernen",
    ["AutoWhitelistFriends"] = "Freunde automatisch auf Whitelist",
    ["DoesntWorkRN"] = "Funktioniert gerade nicht!",
    ["AutoKillEvilKarma"] = "Auto-Kill Böses Karma",
    ["FarmingKillPlayer"] = "Spieler-Kill-Farming",
    ["EnterPlayerUsernameOrDisplay"] = "Spielerbenutzername oder -anzeige eingeben",
    ["TypeUsernameDisplayHere"] = "Benutzername/Anzeigename hier eingeben...",
    ["AutoKillPlayer"] = "Auto-Kill Spieler",
    ["SpectatePlayer"] = "Spieler beobachten",
    ["StopSpectating"] = "Beobachtung beenden",
    ["SelectCrystal"] = "KristallAuswählen",
    ["AutoOpenCrystal"] = "Auto-Kristall öffnen",
    ["SessionTime"] = "Sitzungszeit",
    ["CustomTimer"] = "Benutzerdefinierter Timer",
    ["Start/StopTimer"] = "Timer starten/stoppen",
    ["CurrentStats"] = "AktuelleStatistiken",
    ["GainedStats"] = "GewonneneStatistiken",
    ["PlayerStats"] = "Spielerstatistiken",
    ["PlayerSelector"] = "Spielerauswahl",
    ["ViewPlayerStats"] = "Spielerstatistiken anzeigen",
    ["FPSBOOST"] = "FPS-BOOST",
    ["ServerHop"] = "Serverwechsel",
    ["AutoLift"] = "Auto-Heben",
    ["SpeedGrind(No Rebirth)"] = "Schnelles Grinding (Keine Wiedergeburt)",
    ["HideFrames"] = "RahmenAusblenden",
    ["SelectPet"] = "Haustier auswählen",
    ["AutoOpenPets"] = "Auto-Haustiere öffnen",
    ["AutoOpenAuras"] = "Auto-Auren öffnen",
    ["SelectAura"] = "Aura auswählen",
    ["AutoUseProteinEgg"] = "Auto-Protein-Ei verwenden"
}
